language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - frontend/node_modules

env:
  - TEST_DIR=frontend

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - cd $TEST_DIR
  - npm install -g bower
  - npm install
  - bower install

script:
  - cd $TEST_DIR && npm test
